[workspace]
resolver = "2"
members = [
    "generator/badge/"
]

[workspace.dependencies]
arg-picker = "0.2.0"
just_fmt = "0.2.1"
ab_glyph = "0.2"
image = { version = "0.25", default-features = false, features = ["png"] }
tiny-skia = "0.11"
ureq = "3"

[workspace.package]
version = "0.5.0"
edition = "2024"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mingling-rs/mingling"

[profile.dev]
opt-level = 0
debug = true

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true
